env:
  matrix:
    - ELM_VERSION=0.17.1 TARGET_NODE_VERSION=node

install:
  - npm install -g elm elm-test
  - elm-package install -y
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test

cache:
  directories:
    - elm-stuff/
    - test/elm-stuff/

script:
  - make -w
